apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
spec:
  selector:
    name: mysql-pod
    type: clusterIP
  ports:
  - port: 3306
    targetPort: 3306
  